sudo:
  false

language:
  python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

before_script:
  - moto_server &
  - sleep 10
  - curl localhost:5000

script:
  - make test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: rar/jPOI6WJiX31KgEfiGmhG0ajRmIACP1B3dK9e9V+mC5ApSAf2ihk4wEg0+sZhJRdqAZ6f/2awFHWJq9m0WBTVP7xG6OXSoxwH8r6m3kI8krNjBI+8Y9yJo/z57mq8yXd9QX0OUubvpUP8q0oFGvuOu2ffmZ6on3AHVQZugpnEAE0Eewsloxy/AmwTAPqov76uAIQqYPfHYhIggNT+RVDK98867I/omt1EqlsmubOhJ/8mEzwyE6knTinUYAbh0RGAFwlPmHnzfxtrjmGiH7kZDjxlYXE9+CwmNHVeyJuzA3n+z6ZeRw0rYixPs7cjJf7ccFAa9lBa8Iu9A6sIMbw42rufDAHk4qo7dbGRqqt6Utcrzh8tae+w1+W1nixkkACV4BsWVUrSPxFGnNNkUq4yoa6N8tnAY+f3KxdYRKK+6oukq5xyaprrFjm/YEKV1SdU+eVIkvjC4e+/YGZB+CLaB32eROJtezFcm/d4LVjoqIHgLssKdR32f9YU+GtcZ3dKkP8WuDhv56oZjUMs7nZqZuV1EVeRSUFCc5MWRPwJE4pTcMZCSqkxaQbgmLE271jyP6TSt6lO1hOCi54u52eTohhvls83eIJJ2ESenvlyi9OLLwM7uQQpT7d8Qwg/6BrvY2jyr5x/w1lNu9an6TpB7TxwSI2k2TOmscPK4Gw=
